### ISSUE TITLE
No section-customize in wp 4.4.1

### ISSUE THREAD

**Issue by grapherd** [FameThemes/onepress#10]
In wp 4.4.1, customize.php can't see section-customize

![selection_0016](https://cloud.githubusercontent.com/assets/1785945/12457365/0d4e8fa2-bfdf-11e5-8344-e9c551c627ac.png)

How can I fix that?
thanks!

**Comment by KienTrong** [comment]
If you are running version 1.0.4 then: 

1. Create new page called Home for example.
2. Select Frontpage template for that page.
3. Go to Settings-> Reading and select Home page as your front-page.
4. Back to Customizer and you will see all sections showing up.

The ideal is we only show section settings when the Frontpage template is being used.

**Comment by grapherd** [comment]
@KienTrong Thanks for helping!
