### ISSUE TITLE
Close the mobile menu when click on any menu link.

### ISSUE THREAD

**Issue by congthien** [FameThemes/onepress#103]
There're some clients complain about the mobile menu. 

It should be close when click on any menu link. Of course still keep scroll effect.

**Comment by cnyyk** [comment]
add code below to your child theme's js file

`(function () {
	// toggle mobile dropdown menu after click menu link
	if ( jQuery( '#nav-toggle:visible' ).length > 0 ) {
		jQuery( '.onepress-menu a' ).on( 'click', function () {
			var $om = jQuery( '.onepress-menu' );
			if ( ! $om.hasClass( 'onepress-menu-mobile' ) ) return false;
			$om.slideUp( function () {
				jQuery( '#nav-toggle' ).click();
			} );
		} );
	}
})();`

**Comment by cnyyk** [comment]
![untitled](https://cloud.githubusercontent.com/assets/275233/15365133/aef41640-1d51-11e6-8dbd-79ac42687b11.gif)

**Comment by KovalRomanK** [comment]
How would you add the .js file to the actual theme and have the two work together?

**Comment by KienTrong** [comment]
@KovalRomanK We will review the code from @cnyyk (thank you for that) and will add it into the theme in next version.

**Comment by KovalRomanK** [comment]
Ok thank you.
