### ISSUE TITLE
Miss section-project

### ISSUE THREAD

**Issue by grapherd** [FameThemes/onepress#11]
In 1.0.3, 1.0.4 demo
http://justfreethemes.com/demo?theme=OnePress

I see there is a section `project`
but can't see in wp costumize, will they be in the future update?

thanks.

**Comment by KienTrong** [comment]
@grapherd Thanks for your interested in our theme.
1. OnePress theme is not ready for use, some how the guys over justfreethemes.com pull the theme from wordpress.org review list and public it on their site. You can view the review progress here : https://themes.trac.wordpress.org/ticket/27818
2. The project section will be in our Pro feature and it come with a Custom Post Type.

Cheers.
