### ISSUE TITLE
Could you please add a option to switch footer mail newsletter to search form?

### ISSUE THREAD

**Issue by cnyyk** [FameThemes/onepress#115]
Could you please add a option to switch footer mail newsletter to search form?

Actually, news letter usage is significantly decreased now.

And Home page should add a search entrance, the better place is the footer area, to replace the newsletter area.

And also should add a option to set the search form and social area's position in the footer area, someone may like search form being placed left side, and some others may like the social area being placed left side.

Maybe should consider my suggestion.

**Comment by shrimp2t** [comment]
Hey

The eassiet way is use child theme, just copy file `footer.php` from `onepress` theme to your child theme
So in your child theme you can add/remove/change what will display on your site footer.

**Comment by cnyyk** [comment]
Thanks for reply. Done yet.
