### ISSUE TITLE
Duplicate array element

### ISSUE THREAD

**Issue by Olivia101** [FameThemes/onepress#120]
I just noticed that the array element 'section' appears twice in the code below which appears in "inc/customizer.php"

```php
$wp_customize->add_control( new OnePress_Misc_Control( $wp_customize, 'onepress_order_styling_message',
			array(
				'section'     => 'onepress_news_settings',
				'type'        => 'custom_message',
				'section'     => 'onepress_order_styling',				
			)
		));
```

**Comment by shrimp2t** [comment]
Thanks for your report, 
I've checked but the section `'onepress_order_styling_message` is not appears twice in theme customizer.
