### ISSUE TITLE
The selector ".break" was not found

### ISSUE THREAD

**Issue by Olivia101** [FameThemes/onepress#123]
Compiling the .scss files gives the error below:

Error: "h1" failed to @extend ".break".
>>        The selector ".break" was not found on line 89 of assets/sass/_document.scss
>> >>   @extend .break;

**Comment by cnyyk** [comment]
the .break defined in reset.scss. and reset css has been included in bootstrap.min.css, so the style.scss does not include the reset.scss.

you should add !optional after .break to avoid this error.
same to .clearfix

**Comment by Olivia101** [comment]
"the .break defined in reset.scss. and reset css has been included in bootstrap.min.css"
 I checked and .break does not exist in Bootstrap v4 so I am not sure how OnePress .scss files were compiled
