### ISSUE TITLE
Features disappear in the admin zone

### ISSUE THREAD

**Issue by krysbzh** [FameThemes/onepress#129]
Hello,
I use the last version of Onepress Plus theme and i added 3 columns in the "features" section with icon and description. It appears correctly in my front page. I save and exit the admin zone. 
When I return in the features section, my columns has disappeared of the administration zone. 

I have analysed this issue with the customer support specialist David T. and we found the origin of this problem :
If we insert HTML tags like <ul><li> and style=text-align:left , it disappears.

Could you take a look please ?

**Comment by shrimp2t** [comment]
Hey 
I've tested. It's seem working find http://prntscr.com/cg8nzp
Can you let me know step by step how to find that problems.

And don't forget send me the content which you enter for you features :)

**Comment by krysbzh** [comment]
Hi,
the problem comes when you add more than 1 element (for me 3). 
1. Enter in features section
2. Add 3 elements :
Title 1
fa-search
`
<ul>
 	<li style="text-align: left">Description 1 of the feature 1</li>
 	<li style="text-align: left">Description 2 of the feature 1</li>
</ul>
`
Title 2
fa-camera
`
<ul>
 	<li style="text-align: left">Description 1 of the feature 2</li>
 	<li style="text-align: left">Description 2 of the feature 2</li>
</ul>
`
Title 3
fa-euro
`
<ul>
 	<li style="text-align: left">Description 1 of the feature 3</li>
 	<li style="text-align: left">Description 2 of the feature 3</li>
</ul>
`

Here the capture before saving :
http://prnt.sc/ch0ljv

3. Click on "save and publish button"
4. Click on the cross button to return on the Wordpress dashboard
5. Return in the admin section of features
6. The 3 elements has disappeared :
http://prnt.sc/ch0meh

**Comment by shrimp2t** [comment]
Still can not file this problem.

Please try to disable all plugins exclude "OnePress Plus" plugin.

**Comment by krysbzh** [comment]
The issue has been resolved with the 1.2.5 version. Thanks.
