### ISSUE TITLE
Gallery Section

### ISSUE THREAD

**Issue by KienTrong** [FameThemes/onepress#139]
Click image to lightbox

**Source:**
- [x] Select page
- [x] Facebook album (Plus)
- [x] Instagram ( Plus )
- [x] Flickr ( Plus )

**Layout:**
- [x] Default, inside container
- [x] Full Width

**Display:**
- [x] Grid (Space: 20)
- [x] Carousel
- [x] Slider
- [x] Justified
- [x] Masonry

** Settings:**
* Number of gallery item: Number input, max ...
* Space between image: Number input.
* Click to image: Open lightbox. ( https://github.com/sachinchoolur/lightGallery )

**Comment by shrimp2t** [comment]
https://codex.wordpress.org/Function_Reference/get_post_gallery
