### ISSUE TITLE
There's some unused css rules should be clean

### ISSUE THREAD

**Issue by cnyyk** [FameThemes/onepress#152]
see onepress-plus.php line 2320

$style[ $section['section_id'] ]['bg'] = "background-color: {$bg_color};";

will cause a lot of empty background css, shown as pic attached:

1、small fix, add 

if ( $bg_color) $style[ $section['section_id'] ]['bg'] = "background-color: {$bg_color};";

will be better.

![qq20160623-0 2x](https://cloud.githubusercontent.com/assets/275233/19118951/b854055c-8b50-11e6-94a1-ed6631d208f2.png)

2、if a section not shown on homepage but set background or color, will echo these never used css rules to html, should be improved.

**Comment by shrimp2t** [comment]
Hi,

This issue fixed in OnePress Plus version 1.1.5 that will available soon :)
