### ISSUE TITLE
Text over Hero image / black or white banner under Hero picture - when resizing browser

### ISSUE THREAD

**Issue by TheElephant1979** [FameThemes/onepress#153]
When I make the browser smaller the Hero section responsiveness is functioning correctly and letters in the Hero section become smaller but the text and the pictures below will move up and will be upon the picture used in the Hero section.
When I maximize the browser again a black (or white; you have to look very good here) banner will be pushed in, directly below the Hero picture, when the text which is over the Hero picture increases in size.

Issue also seen by David T. | Customer Support Specialist
(Thanks for feedback here. I saw the issue you talk about. Please create an issue here ... github).

**Comment by KienTrong** [comment]
@TheElephant1979 You will need to refesh the page to see if the overlap still happen or check the site on real device to see.

We are prepare to release OnePress to next version but didn't find this issue on real device.

**Comment by TheElephant1979** [comment]
Hi,

Agree, but it does happen  when you resize the browser as described before.

Up to you to fix it or Keep it as a known issue.

I'm only the messenger.

Thanks for the awesome theme!

Jack

Op 1 nov. 2016 9:49 a.m. schreef "Kien Trong" <notifications@github.com>:
