### ISSUE TITLE
Eliminate js and css render blocking?

### ISSUE THREAD

**Issue by grapherd** [FameThemes/onepress#16]
For the page loading speed issue, 
will this theme try to eliminate js and css render blocking ?

thanks!

**Comment by KienTrong** [comment]
What do you mean about "eliminate js and css render blocking"?

**Comment by grapherd** [comment]
When using [google pagespeed insight](https://developers.google.com/speed/pagespeed/insights/) to analysis wordpress which using onepress theme, it gave me this error.

**Comment by KienTrong** [comment]
The theme is not optimize yet as it's under review by WordPress review team :)
