### ISSUE TITLE
1.0.9 does not work properly on wordpress 4.4.2

### ISSUE THREAD

**Issue by mduchateau** [FameThemes/onepress#18]
Hi,

Thanks for the great theme and the active development !

The 1.0.3 works like a charm on a new fresh installed wordpress (4.4.2).
The version 1.0.8 and 1.0.9 seem broken : only header, menu and footer are shown. 

I get the same results with different servers or different installations.
Can you confirm me you observe the same issue ?

Thanks.
Kr,
Michel

**Comment by KienTrong** [comment]
Thanks for your kind of words.

You downloaded and use the theme before it get public so it has conflict with new version ( I guess you downloaded it from justfreethemes )

1. In version 1.0.3 we used Customizer to handle the front page content and it's not allow by wordpress.org review team ( https://themes.trac.wordpress.org/ticket/27818#comment:12 )

2. In version 1.0.9, the theme review team force us to change the way the front page data being handle and they suggest us to use page content and you can select page from customizer. That way you won't lost any content when switch to other theme.

Let me know if it helped.
