### ISSUE TITLE
Can't change section services icon, always display a flag icon

### ISSUE THREAD

**Issue by cnyyk** [FameThemes/onepress#197]
OnePress latest, version 1.3.0.
Bug described below:
Customizer,
Service section,
Add a item, choose icon, pick a icon.
Add second item, choose image, pick a image.
Add third item, choose icon, pick a icon.
Save and publish.

There's three item in service section, 1st and 3rd shown "Flag" as it icon( not the icon chosen in customizer ), 2nd is ok, image as icon.

**Comment by congthien** [comment]
@cnyyk 

Did you update the latest OnePress v1.3.3 ?

**Comment by cnyyk** [comment]
not yet. i'll try the latest onepress.
