### ISSUE TITLE
Increasing 'team' from 4 members to 8

### ISSUE THREAD

**Issue by holgardk** [FameThemes/onepress#20]
Is there an easy tweak for this?  I need to have 8 team members and not 4... Not sure how to create a second row.

Thanks!

**Comment by KienTrong** [comment]
Thanks for use our theme, which version of OnePress you are running?

**Comment by holgardk** [comment]
I'm running Version: 1.0.9

**Comment by KienTrong** [comment]
In version 1.0.9 we pull site users as team member. Do you have difficult to add team member profile image?

It's because we are working on it and want to replace it with simpler solution, just upload profile image for each member and pull the image title as name, image description as bio info.

**Comment by holgardk** [comment]
I have not added images yet (I believe I need to do that in a third party host... correct?) but I think I can figure that out.

My issue is that the site has a max of 4 team members to be displayed.  I have 8 team members - can you increase the number of team members the site can display?

**Comment by holgardk** [comment]
Another feature would be to reorder the sections... but not completely needed.

**Comment by KienTrong** [comment]
More team members options is available via OnePress Plus plugin which is a premium plugin we are working on. It's ready for launch but we need to tweak a bit for Team section as we talked above.

Don't worry about the OnePress Plus pricing, you can try it before purchase to know if it suit your need :)

**Comment by KienTrong** [comment]
Reorder: Something like this? : http://cl.ly/3J3N1m1C2U26 :dancers:

**Comment by holgardk** [comment]
Both sound great!

The page is for a charity fundraiser so I can't justify spending money on the premium plug in.  How much is it going to be and when will it be available?

**Comment by KienTrong** [comment]
It's live here : https://www.famethemes.com/themes/onepress/

**Comment by holgardk** [comment]
Thanks Kien- my team doesn't want me to spend $$ on this effort (every penny counts).  Thanks though!

This template is by far the easiest and cleanest to use wordpress site!

**Comment by KienTrong** [comment]
Let me know your charity a bit more, a free license won't a big deal ;)

**Comment by holgardk** [comment]
http://climb4kids.com/

Our goal is to raise $20,000 for the Big City Mountaineers through fundraising and at least one event.  We are almost ready to kick off the campaign once I get the site all finished up.

**Comment by KienTrong** [comment]
Let's register an account at our website and let me know your FameThemes username here :)

**Comment by holgardk** [comment]
holgardk - Thanks!

**Comment by KienTrong** [comment]
You should receive a receipt email, any feedback via Github issue would be great :)
