### ISSUE TITLE
parallax image is zoomed and not center

### ISSUE THREAD

**Issue by congthien** [FameThemes/onepress#204]
a site for example : http://www.omni5media.com/

**Comment by AgnesFaid** [comment]
Hi, 
I agree with you, I ask the same question here before : background image in Hero section 
and no rely :(

**Comment by congthien** [comment]
@AgnesFaid 

thanks for your feedback. We will update in next version.

**Comment by AgnesFaid** [comment]
ok great, thanks !! :)

**Comment by shrimp2t** [comment]
Let, try to update latest version, this site using old version of onepress.
