### ISSUE TITLE
 Section: Video Lightbox - Background image not displaying

### ISSUE THREAD

**Issue by markacronin** [FameThemes/onepress#205]
The background image in the Video Lightbox section no longer displays after updating to 1.3.5?

**Comment by markacronin** [comment]
It does appear zoomed and not centred in some browsers? But not at all in others...

**Comment by shrimp2t** [comment]
Please update to version 1.3.6 and don't forget clear cache and reset CDN if use.

**Comment by markacronin** [comment]
Great! Issue resolved. Thank you!
