### ISSUE TITLE
onepress services section text doesn't change

### ISSUE THREAD

**Issue by sdffdssdffds** [FameThemes/onepress#219]
Hi,
the service section shows the default nonsense text after I edit and update the Service corresponding pages. The titles of the services are updated normally but the containing text remains the standard nonsense text. What am I doing wrong?

**Comment by congthien** [comment]
Hey there,

It is not a bug. Please read here : http://docs.famethemes.com/article/57-how-to-change-wordpress-page-excerpt-content

Also please contact us here if you have any issue : https://www.famethemes.com/contact/

**Comment by sdffdssdffds** [comment]
Thanks a lot! It works great.
