### ISSUE TITLE
Onepress hero background image offset when parallax option selected

### ISSUE THREAD

**Issue by mloeckle** [FameThemes/onepress#220]
When the page is first loaded the background image is out of place and pops into its correct position once the page is scrolled. I can reproduce the problem using the base installation with the included hero5.jpg image. I have tried Safari, Firefox and Chrome. The problem only occurs when parallax is enabled.

**Comment by mloeckle** [comment]
Can I get some help on this please?

**Comment by mloeckle** [comment]
Thank you!  Looks like it addresses #223 as well?  How long will it be before that makes it's way into production?

**Comment by shrimp2t** [comment]
Hi, New version will available on next version soon, maybe tomorrow.
