### ISSUE TITLE
Issues when updating from 1.1.8 to the last version

### ISSUE THREAD

**Issue by aznsilence** [FameThemes/onepress#221]
Hello guys,

I have some issues when i try to update from 1.1.8 to the last version i get this error message : 
The update failed: The download failed. Unauthorize.

Please can you help me to fix this problem.

Thank you 

Best regard,

**Comment by shrimp2t** [comment]
Hi,

Now the latest version of OnePress is 1.3.8.

I think you're talking about OnePress Plus, please send us your information to customercare@famethemes.com
