### ISSUE TITLE
Hero background disappears

### ISSUE THREAD

**Issue by mloeckle** [FameThemes/onepress#226]
v1.4.  If you scroll to the bottom of the home page and then click the site title to auto scroll back to the top, the hero background is missing.  The moment you scroll up or down, the hero background pops back into view.  This only happens when parallax is enabled.  Also, when the page is at the top, the initial scrolling is jumpy.

**Comment by congthien** [comment]
Hi @mloeckle 

What is your site URL ?

**Comment by mloeckle** [comment]
Www.microsage.com<http://Www.microsage.com>

Michael Loeckle
Microsage, Inc.
(817) 469-6211 x200

On Jul 27, 2017, at 11:31 PM, congthien <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @mloeckle<https://github.com/mloeckle>

What is your site URL ?

-

**Comment by mloeckle** [comment]
Has there been any progress on the hero image disappearing?

I used the recommended workaround on #228 for the jumpy scrolling so that part is fixed.  I put .site-header { position: fixed; } in the additional css section.

**Comment by shrimp2t** [comment]
8cc36568cce564402997f1d6f94e886e2413f21b

**Comment by shrimp2t** [comment]
see #228
