### ISSUE TITLE
Team

### ISSUE THREAD

**Issue by georgeg1a** [FameThemes/onepress#23]
Hi,
I just installed one press 1.1.2 with the new team-member adjustments :)
What I still miss a bit is a link to a new side with a long text about the team members, and just a small text in the overview (like in 'about' and 'services')
George

**Comment by shrimp2t** [comment]
Hey
Now the team data changed to media attachment data.

So the title of the image become to name of team member, and the attachment description become to member position.

I hope to use this change would be more useful for editing member details than select an existing user for each member.

![team-edit](https://cloud.githubusercontent.com/assets/1811807/13031305/8e2b62ba-d2fb-11e5-8928-792b2e67bd73.png)

**Comment by georgeg1a** [comment]
:)
