### ISSUE TITLE
Jetpack compatible

### ISSUE THREAD

**Issue by congthien** [FameThemes/onepress#230]
It is very popular plugin. When install, the onepress editor in Customize does not work.

**Comment by congthien** [comment]
https://github.com/Automattic/jetpack/issues/7598

**Comment by kraftbj** [comment]
Noting that the fix for this on the Jetpack side will ship out no later than our September release, which is currently scheduled for September 5th.

**Comment by shrimp2t** [comment]
This issue seem fixed on latest version of Jetpack.
