### ISSUE TITLE
Hero image disappears

### ISSUE THREAD

**Issue by mloeckle** [FameThemes/onepress#236]
If you scroll to the bottom of the home page and then click the site title to auto scroll back to the top, sometimes the hero image is missing. The moment you scroll up or down, the hero background pops back into view. This only happens when parallax is enabled.
[Untitled.mov.zip](https://github.com/FameThemes/onepress/files/1263981/Untitled.mov.zip)

**Comment by mloeckle** [comment]
Can I get an update on this please?

**Comment by mloeckle** [comment]
This problem is still present in the latest version (2.0.2).

**Comment by shrimp2t** [comment]
see #277
