### ISSUE TITLE
Team Member Adds

### ISSUE THREAD

**Issue by holgardk** [FameThemes/onepress#24]
<img width="297" alt="screen shot 2016-02-13 at 2 20 34 pm" src="https://cloud.githubusercontent.com/assets/17186795/13030373/8c4dfb2c-d25d-11e5-815e-b74db9f21df0.png">

I can't select a team member to add, facebook is listed twice and no instagram or twitter (would be cool to add a 'crowdrise' logo one for fundraising).  I assume this is a bug - would like to add a picture, title and subtitle to each team member without having to use the avatar external webpage as well.

**Comment by shrimp2t** [comment]
Hi
Now team  member data changed to image attachment data, when you click to "Add" button a media popup will open the you can select member picture, see #23

**Comment by KienTrong** [comment]
We are working on an update for the Plus plugin, remember to put your license code into Appearance -> OnePress -> Auto Update in order to enable auto update.
