### ISSUE TITLE
Mobile menu not displaying correctly.

### ISSUE THREAD

**Issue by joshcaple** [FameThemes/onepress#240]
I've added some code to onepress to change the toggle colour and make it visible..
__### #nav-toggle span, #nav-toggle span:before,
_#nav-toggle span:after { background: #666; }___

Now I'm not sure how to;
-Change the colour of the X in the expanded menu button
-Get rid of the 'Menu' word that has started appearing in the background of the toggle 

Thanks!

**Comment by congthien** [comment]
What is your site URL ?

**Comment by joshcaple** [comment]
Atlasaccess.net

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by congthien** [comment]
Sorry I forgot to tell you this option is available : https://cl.ly/3y3W002a2G0i

also to remove the Menu word, just update the latest version.
