### ISSUE TITLE
Gallery broken in Chrome 62 on Win 8.1

### ISSUE THREAD

**Issue by tilmanbremer** [FameThemes/onepress#246]
I use the OnePress theme for a couple of days now and I noticed that the gallery is broken in Chrome, while it works in Firefox. I thought it was an error on my side configuring the theme, but the gallery on the demo site is broken for me too. The row doesn't fit in the screen and so it breaks after 4 images instead of 5.
This is https://demos.famethemes.com/onepress/ for me:

![onepress](https://user-images.githubusercontent.com/20415107/32143229-acff4fd0-bca6-11e7-9200-7feb2de22a02.PNG)

I just tried it in Chrome on another machine and could not (!) replicate the error. I couldn't figure out what is the cause. I tried deactivating adblocker plugins etc. but that didn't help.

My main machine has a quite large resolution of 2560x1440 so I thought that might be the problem, but the gallery is in fact broken even for resized browser windows. It seems to be always too wide for the window size:
![onepress2](https://user-images.githubusercontent.com/20415107/32143300-85124b98-bca7-11e7-8ae5-7817f7e038f2.PNG)

Sorry that I cannot provide more helpful information, hopefully you can replicate the problem somehow. If there is anything you would like me to try, I am happy to help.

**Comment by congthien** [comment]
Hello,

I checked our demo on my Chrome and don't see any problem:
https://cl.ly/300Y0K1o323f

**Comment by tilmanbremer** [comment]
Thank you for having a look at this. I imagine it is not very easy to work on that if you can't replicate the error. I tried another time to find anything that might cause this, different machines, different browsers. I couldn't find a pattern. What I think is worth mentioning: The images are positioned slightly incorrect in Chrome, instead of left: 20, 40, 60 % etc. it is something like 20,0814, 40,1628% etc. when I checked the DevTools. Of course when the fourth image is positioned left: 60,2938% with a width of 20% the last one doesn't fit in the row anymore. Here is the DevTools view:

![chrome](https://user-images.githubusercontent.com/20415107/32164695-92d78810-bd60-11e7-80bb-b7ff40bb3585.PNG)

**Comment by KienTrong** [comment]
@tilmanbremer I make a test too and it looks good on my Chrome : https://cl.ly/0H0a033g2P1k , my mac resolution is: 15.4-inch (2880 x 1800).

Also, I suggest you test the mobile mode on real devices :)

**Comment by tilmanbremer** [comment]
The theme responds correctly on my main PC with firefox, too, and two other laptops with multiple browser and also on my phone. So I tested with real mobile devices.

Like I said, it is simply broken on my main machine with Chrome. I just want to find out why it doesn't work on that machine. It doesn't help that it works on other machines and in other browser. As long as it doesn't work on one, and I can't figure out why, there is always a chance that it is broken for some of my visitors, too.

**Comment by KienTrong** [comment]
Hi @tilmanbremer I understand your concern.

Could you try to use Incognito Chrome mode to test? also when resize your browser try to reload the page if it cause the issue.

**Comment by tilmanbremer** [comment]
Okay, I just tried in incognito mode. I deleted the cache first, and also reloaded the side with the resized browser window. No changes, unfortunately.

**Comment by tilmanbremer** [comment]
It has been quite some time until I last heard from you. What is the situation? Could you figure out the problem?

**Comment by KienTrong** [comment]
We couldn't replicate the issue, I would wait for the next version and check again.
