### ISSUE TITLE
Problem with menu on tablet and smartphone

### ISSUE THREAD

**Issue by georgeg1a** [FameThemes/onepress#27]
I have a problem with the menu: the submenu.
On PC all looks fine, but on tablet and smartphone the submenu is lost....
<img width="981" alt="screenshot 2016-02-20 22 18 53" src="https://cloud.githubusercontent.com/assets/17223749/13199234/0198a0f4-d820-11e5-8b49-7e3739844e49.png">
<img width="495" alt="screenshot 2016-02-20 22 19 03" src="https://cloud.githubusercontent.com/assets/17223749/13199235/01d6e774-d820-11e5-98af-3cb21c4a777f.png">

**Comment by shrimp2t** [comment]
I've checked on my iPad, it's working fine.

You're trying to add new menu above the main menu ?.
if Yes:
Maybe your code conflict with this code of theme,so you need to fix it.
if No: Which device name you are testing with ?

**Comment by georgeg1a** [comment]
Maybe I was not so clear:
Www.weserstudio.de
On my menu-item: 'shootingpreise', I added 2 sub-items: 'fotoshootings' and 'hochzeitsshooting'.
But as you can see on my screenshots above, the sub-items not show on my iPad 3, iPhone 5, 6 or even on my laptop, when I make the screen smaller
