### ISSUE TITLE
Child Theme not working with PHP 7.1

### ISSUE THREAD

**Issue by jannorthoff** [FameThemes/onepress#273]
Hello there!

On child theme activation WP throws:

Warning: Illegal string offset 'custom_css_post_id' in /var/www/html/wp-includes/theme.php on line 903

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/theme.php:903) in /var/www/html/wp-admin/includes/misc.php on line 1114

This breaks f.ex. the customizer.

When the Master Theme is activated it behaves as expected, all fine...

We use it here:
bitcoin-beratug.berlin
(you might need to refresh page)

Thanks for your advice.

Greetings,
Jan

**Comment by shrimp2t** [comment]
Hi,

OnePress already support child theme.

You got this error because your theme have problems.

Check https://developer.wordpress.org/themes/advanced-topics/child-themes/ for more details.
