### ISSUE TITLE
remove copyright from footer

### ISSUE THREAD

**Issue by AgnesFaid** [FameThemes/onepress#274]
Hi everybody,
Before the last update (2.0.2), I changed copyright in footer in template-tags.php. But now, the code has changed and I think I have to do these changes in footer.php, but it's not clear. 
Could you help me ?
Thanks,
Agnes

**Comment by AgnesFaid** [comment]
I've found it's ok.
For those who are interested, it's here : https://www.youtube.com/watch?v=oC7X0kmzMTg

**Comment by shrimp2t** [comment]
Hi,

We've improved footer to make it better and clear.

Remove footer copyright is not recommended on this version.
However if you want to change it, see here https://github.com/FameThemes/onepress/blob/master/inc/template-tags.php#L1326

**Comment by AgnesFaid** [comment]
Thank you for your reply.
I would like to keep footer copyright but my client doesn't want to change anything on his website.
Agnes
