### ISSUE TITLE
Links to other pages with "#" will not work.

### ISSUE THREAD

**Issue by dnunes** [FameThemes/onepress#280]
I added a link in the format "/page/#something" and it doesn't work. The problem is in the selector in the theme.js, line 401 (https://github.com/FameThemes/onepress/blob/master/assets/js/theme.js#L401). The ideal solution would be kind of complex, but a better selector (with its own kind of problems) would be `|=["#"]` rather than `*=["#"]`.

It would not work when you have a link that includes a path, even if the path resolves to the current page, but wouldn't render any links unusable as the current selector does. I'm willing to create some pull request for small fixes in the template if that's acceptable.

**Comment by shrimp2t** [comment]
Hi,

I tried with your solution but it not working find.

The selector `|=["#"]` will selects elements that have the specified attribute with a value either equal to a given string or starting with that string followed by a hyphen (-). 

This issue will working find in home page, but not for other pages. You can't back to home page with this anchor.

See https://api.jquery.com/attribute-contains-prefix-selector/

**Comment by dnunes** [comment]
Oh, I'm sorry, I typed the wrong selector in here. I meant the "start with selector" (`^=`) and ended typing the "prefix" selector in here.

https://api.jquery.com/attribute-starts-with-selector/

Let me explain a little bit better: the current solution, using "contains", will render any link for other pages and for external sites with an anchor in it (imagine a link for "anothersite.com#section2") useless, as it will try to use the "scroll to" effect but wouldn't find that anchor on the current page and would prevent the navigation to work.

Changing to "start with selector" will disable the effect of your link contains a full address or a more complete reference to the anchor including the page, even if you currently are on the target page. Eg: of you are at "page.com/home" and the href is "page.com/home#anchor" it would not use the effect, but I think not having the nice effect in specific cases is a better compromise than having links that doesn't work in specific cases.

**Comment by shrimp2t** [comment]
This is good idea and it will be ok if we have 2 menus: one for home page and one for other pages.
On current version we just have one. So if apply your idea for this menu you still can not back to home page from other pages.
