### ISSUE TITLE
appearance of testimonials section

### ISSUE THREAD

**Issue by AgnesFaid** [FameThemes/onepress#286]
Hi,
I'm wondering if it's possible to change the appearance of the testimonials. I explain : I've now 4 testimonials : 3 are on the same line and with the same size, but the 4th is under and take all the width. You can see it on my screenshot attached.
![testimonials](https://user-images.githubusercontent.com/26567744/37556577-985501d2-29f8-11e8-9de7-30995e8d5169.jpg)

Could you tell me if it's possible to have the 4th testimonial with the same size of the others ? Or better : have an horizontal scrolling ?
Thanks for your reply,
Agnes

**Comment by congthien** [comment]
Hi @AgnesFaid ,

Please contact us here if you have any issue: https://www.famethemes.com/contact
