### ISSUE TITLE
WP Mail SMTP by WPForms compatible

### ISSUE THREAD

**Issue by congthien** [FameThemes/onepress#303]
When I activated this plugin, it shows error:

`Fatal error: Uncaught Error: Call to undefined function tgmpa() in /Applications/MAMP/htdocs/fame/onepress/wp-content/themes/onepress/functions.php:397 Stack trace: #0 /Applications/MAMP/htdocs/fame/onepress/wp-includes/class-wp-hook.php(286): onepress_register_required_plugins('') #1 /Applications/MAMP/htdocs/fame/onepress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #2 /Applications/MAMP/htdocs/fame/onepress/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #3 /Applications/MAMP/htdocs/fame/onepress/wp-content/plugins/wp-mail-smtp/src/TGMPA.php(410): do_action('tgmpa_register') #4 /Applications/MAMP/htdocs/fame/onepress/wp-includes/class-wp-hook.php(286): WPMailSMTP\TGM_Plugin_Activation->init('') #5 /Applications/MAMP/htdocs/fame/onepress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #6 /Applications/MAMP/htdocs/fame/onepress/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #7 /Applications/MAMP/htdocs/fame/onepress/wp-settings.php(450): do_action('init') in /Applications/MAMP/htdocs/fame/onepress/wp-content/themes/onepress/functions.php on line 397`

**Comment by shrimp2t** [comment]
See https://github.com/FameThemes/onepress/commit/40ab06894f7642a4afb506d134ad5cfa692cb319

This theme do not use tgmpa anymore
