### ISSUE TITLE
More News button link

### ISSUE THREAD

**Issue by congthien** [FameThemes/onepress#305]
See: https://cl.ly/2Z0E3B1d3J1O

Replace the input field with a page drop-down. And set it is the Posts page as default, also hide it if no page is selected.

Reason:
`why doesn't it actually offer a list of pages - asking for URLs is really, really, really bad practice because site URLs change and I don't want to hack through the entire theme looking for manually entered ones`

**Comment by KienTrong** [comment]
Agree, there should be an option: Select Pages or Custom Link.
