### ISSUE TITLE
There is a weird skipping issue when scrolling up or down

### ISSUE THREAD

**Issue by congthien** [FameThemes/onepress#345]
Report by user:
Here is the undesired behavior: https://streamable.com/57ty7

**Comment by chris1000** [comment]
Has there been any progress in terms of fixing this?

**Comment by congthien** [comment]
Hi @chris1000 

Please update the latest version and clear the Safari cache then check again.

**Comment by chris1000** [comment]
Just following, I'm still having this issue. iOS 12.3. Cleared Cache, open in private mode.
