### ISSUE TITLE
Fix for scrolling issue caused by editor-style.css in Visual mode when Classic Editor plugin is activated

### ISSUE THREAD

**Issue by gserafini** [FameThemes/onepress#382]
This happens using a fresh install of WordPress 5.1.1, OnePress 2.4.2 and Classic Editor 1.4 plugin (current latest versions of each).  After Classic Editor plugin has been activated, if in Visual mode, the edit box expands to the bottom of the screen, and increases in height every time a key is pressed or on mouse-up if a click is made inside the edit box.  This doesn't happen with Text mode.  It becomes very difficult to edit when the screen jumps around.

**Solution:**
If you remove / comment out line 7 from the HTML editor-style.css:
`height: 100%;`
it seems to fix this issue.

No observed adverse effects from removing height: 100% from the html declaration, and it fixes the height jumping / scrolling issue.

I think what is happening is that there's code in core WordPress to re-calculate what the height of the edit box should be that fires every time key-up or mouse-up happens in the box (this is what expands the height of the box to fit the content once you reach the bottom of it).  Somehow having the `html { height: 100%; }` bit in the editor-style.css file causes the box to grow uncontrollably large, and scroll unintentionally.

Thanks for the great theme and your add-on plugin, I've used it on a number of sites now, so if it's possible to incorporate this fix that would be great.  I can submit a pull request if needed, but the fix for this is literally removing line # 7 from the editor-styles.css file.

**Comment by congthien** [comment]
Hi @gserafini 

Thanks for your feedback. We fixed this issue already and it will be merged in the next version.

See issue #375
