### ISSUE TITLE
Unable to update OnePress Plus

### ISSUE THREAD

**Issue by holgardk** [FameThemes/onepress#47]
![image](https://cloud.githubusercontent.com/assets/17186795/13510710/b0e6d72c-e146-11e5-8004-089c89cd63d6.png)

**Comment by shrimp2t** [comment]
Hey!
Thanks for your report.

Because you are using OnePress Plus plugin so could you open new ticket at https://www.famethemes.com/dashboard/tickets/ send your private site info ( example, your famethemes username, purchase number, ..) ?

Regards.
