### ISSUE TITLE
[BUG] 2.3.7 release broke saving profile data

### ISSUE THREAD

**Issue by T-bond** [FameThemes/onepress#472]
This commit: https://github.com/FameThemes/onepress/commit/fb6d6d050a8a38296170ae0adeb1ab7d64ca899c
makes the Wordpress profile update die on save.
See attached image:
![image](https://github.com/FameThemes/onepress/assets/3778556/56beb6f8-c7b3-414a-8fdc-e0990f13137a)

**Comment by ronh** [comment]
Also other Wordpress setting cannot be saved, same error.

**Comment by shrimp2t** [comment]
This issue already fixed 8ec1e67079b7c247994803239aae7b9dbe2ed445
