### ISSUE TITLE
Wordpress Update 6.7 causes an error with OnePress and Onepress Plus

### ISSUE THREAD

**Issue by boy8xnoname** [FameThemes/onepress#478]
When I updated to WP 6.7.0, it caused an error with onepress-plus Version 2.3.8. I have attached the error below and all my site/server information. If I turn the Debug mode on my site, the error will cause my site to crash. I did a little research, and this is a common issue with plug-ins. I hoped the upgrade to 6.7.1 would address the problem, but it did not. Please update your plug-in to repair this, as I think this issue is slowing my site down.

WP Version: 6.7.1
PHP version: 8.0.6 (Supports 64bit values)
MySql version: 8.0.31

PHP Notice: Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>onepress-plus</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in D:\hshome\langer\langerent.com\wp-includes\functions.php on line 6114

**Comment by shrimp2t** [comment]
The notice come from OnePress Plus plugin.
