### ISSUE TITLE
Broken layout issue on Services section

### ISSUE THREAD

**Issue by congthien** [FameThemes/onepress#54]
![screenshot at mar 14 13-47-49](https://cloud.githubusercontent.com/assets/5317804/13736972/019f5510-e9ec-11e5-8ced-a90c3582727c.png)

It due to the excerpt.

**Comment by KienTrong** [comment]
@congthien Any solutions to fix it?

**Comment by shrimp2t** [comment]
i have plan to fix it but need  customizer done before todo this.

**Comment by congthien** [comment]
Try this : 
```
#services .col-sm-6:nth-of-type(odd) {
clear : both;
}
```

Or use wp_trim_word ?
