### ISSUE TITLE
Can't change Hero Text

### ISSUE THREAD

**Issue by fahimk** [FameThemes/onepress#61]
It won't let me change the Hero Large Text. I tried disabling the Visual Editor, but still didn't work.

<img width="846" src="https://cloud.githubusercontent.com/assets/857824/13907866/c173b364-eeb4-11e5-8e42-a1c62d032d62.png">

**Comment by fahimk** [comment]
had to disable a plugin

**Comment by ajitgoel** [comment]
What plugin was this? I am also having the same issue

**Comment by KienTrong** [comment]
@ajitgoel You can disable all plugin and check again, after that active plugin one by one you will see which plugin is caused this issue.

**Comment by bdowling44** [comment]
Anyone know what the plugin was? Having the same issue.
