### ISSUE TITLE
[Urgent] The navigation doesn't work on WP 4.5 

### ISSUE THREAD

**Issue by congthien** [FameThemes/onepress#79]

**Comment by cnyyk** [comment]
I've been fixed this issue and create a pull request #80.
A js error of jQuery selector syntax caused this problem.

**Comment by congthien** [comment]
@cnyyk Thank you :)

**Comment by KienTrong** [comment]
@cnyyk Thank you for the PR, our dev already fixed it however he commit to wrong branch.
Will merge your pull request later today and release the new version to wp.org.

**Comment by cnyyk** [comment]
@KienTrong You're welcome, it's my pleasure. Thanks for providing the awesome theme.

Now I'm thinking to purchase onepress plus as my studio's website's theme, because I need the projects and testimonials module.

**Comment by KienTrong** [comment]
Go ahead, I just create a coupon FT30 for 30% off just for you ;)

**Comment by cnyyk** [comment]
Wow, really appreciate. I'm doing purchase now.
