### ISSUE TITLE
Add an option to change footer background color.

### ISSUE THREAD

**Issue by congthien** [FameThemes/onepress#82]

**Comment by KienTrong** [comment]
@congthien Do you able to do this issue and commit to `development` branch? 

1. The option should be in : Customizer -> Theme Option -> Site Color -> Name: Footer Background Color + Site Info Background Color ( Also back to top button )

2. The output css can easily add to : https://github.com/FameThemes/onepress/blob/master/inc/template-tags.php#L285

**Comment by congthien** [comment]
OK. Let me try!

**Comment by KienTrong** [comment]
@congthien any news on this one?
