### ISSUE TITLE
Update site demo to latest version.

### ISSUE THREAD

**Issue by congthien** [FameThemes/onepress#83]

**Comment by KienTrong** [comment]
@congthien Any issues yet?

**Comment by congthien** [comment]
It seem the breadcrumb doesn't work on Category : http://demos.famethemes.com/onepress/category/apps/

**Comment by KienTrong** [comment]
@congthien Can you fix it and commit to `development` branch?

**Comment by KienTrong** [comment]
@congthien Does this issue get fix?

**Comment by congthien** [comment]
You can close this. Because it is working now :D
