### ISSUE TITLE
jetpack compatible.

### ISSUE THREAD

**Issue by congthien** [FameThemes/onepress#84]

**Comment by congthien** [comment]
It seem widget or map module of jetpack.

**Comment by shrimp2t** [comment]
@congthien  please explain more details how it is not work.
Just checked the widgets seam working fine.

**Comment by shrimp2t** [comment]
Jetpack Extra Sidebar Widgets error, also it's not working with default theme.

**Comment by skeetcannon** [comment]
Hi guys, any update on the jetpack compatibility? I'm wanting to upgrade one press but holding off until this can be resolved. JetPack is critical.
